# Generated by Django 4.0.3 on 2022-03-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_ouruser_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
