# Generated by Django 4.0.3 on 2022-03-21 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=60)),
                ('edition', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=256)),
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('subjects', models.CharField(max_length=60, validators=[myapi.models.subject_validate])),
                ('rating', models.FloatField(null=True)),
                ('books_available', models.CharField(max_length=60)),
                ('book_Image_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=256)),
                ('due_date', models.DateTimeField(null=True)),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='myapi.book')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Fine',
            },
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 0.0), ('rating__lte', 5.0)), name='rating_range'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('ISBN__length__gte', 13), ('ISBN__length__lte', 13)), name='ISBN_Length_range'),
        ),
        migrations.AlterUniqueTogether(
            name='fine',
            unique_together={('user_id', 'book_id')},
        ),
    ]
