# Generated by Django 4.0.3 on 2022-03-23 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fine',
            old_name='amount',
            new_name='amount_due',
        ),
        migrations.AddField(
            model_name='fine',
            name='amount_paid',
            field=models.FloatField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Issued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(null=True)),
                ('issued_date', models.DateTimeField()),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='myapi.book')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Issued',
                'unique_together': {('user_id', 'book_id')},
            },
        ),
    ]
