# Generated by Django 4.0.3 on 2022-05-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=100, null=True)),
                ('end_time', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=300)),
                ('image_url', models.URLField(null=True)),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
