# Generated by Django 4.0.3 on 2022-03-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('myapi', '0005_delete_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='book_id',
            field=models.ForeignKey(db_column='book_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fine',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterUniqueTogether(
            name='fine',
            unique_together={('user_id', 'book_id')},
        ),
        migrations.AlterModelTable(
            name='fine',
            table='Fine',
        ),
    ]
