# Generated by Django 4.0.3 on 2022-05-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
