# Generated by Django 4.0.3 on 2022-05-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issued',
            name='is_issued',
            field=models.BooleanField(db_column='is_issued', default=False),
        ),
    ]
